version: '3.3'
services:
  nginx:
    image: nginx
    ports:
      - 80:80
    configs:
     - source: default.conf
       target: /etc/nginx/conf.d/default.conf
     - source: nginx.conf
       target: /etc/nginx/nginx.conf
  echo:
    image: keshavprasad/echo:v1
    ports:
      - 4000:4000
configs:
  default.conf:
    external: true
  nginx.conf:
    external: true
